{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c58186dd",
   "metadata": {},
   "source": [
    "# 📊 进阶实战：VoC 客服文本深层诊断与 3D 交叉分析\n",
    "\n",
    "**🎯 核心目标**：打破单维度的“算词频”框架，将【原始文本】转化为具有【业务指导意义】的行动点(Actionable Insights)。完全契合真实的 P7 业务落地复盘。\n",
    "\n",
    "**👨‍💻 面试踩分点 (Senior DA 定位)**：\n",
    "1. **分而治之 (Divide & Conquer)**：不盲目把全品类混在一起跑 LDA，而是在特定的**客询主题标签 (Category)** 下单独进行词频诊断。\n",
    "2. **三层过滤体系**：引入自定义停用词、N-gram 短语提取 (而不仅是单字提取)，以及“差评 vs 好评”的 **Delta 权重作差**，找出真正的痛点元凶。\n",
    "3. **3D 交叉分析机制**：单纯的文本没意义，加入 **用户价值 (user_tier)**、**行为变异 (is_repeat_caller)** 维度做交叉定级。\n",
    "4. **闭环落地 (Closed-loop)**：抽出带有高危短语的长文本原句，形成完整证据链，重现**「法国市场驿站退款 URL 配置错误」**的真实业务断点排查过程。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "10b2fd08",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "plt.rcParams['font.sans-serif'] = ['Arial Unicode MS'] # Mac中文支持\n",
    "plt.rcParams['axes.unicode_minus'] = False"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a37ef145",
   "metadata": {},
   "source": [
    "## Step 1: 模拟真实业务数据 (Mock Data Generation)\n",
    "为了完美还原面试经历，我们将生成包含 `user_tier` (高价值/普通), `is_repeat_caller` (近期重复进线), `market` ( FR/US/UK ) 的数据集，并埋入对应的业务故障案发现场。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b62eb80b",
   "metadata": {},
   "outputs": [],
   "source": [
    "np.random.seed(42)\n",
    "n_samples = 3000\n",
    "\n",
    "# 1. 基础维度生成\n",
    "markets = np.random.choice(['US', 'UK', 'FR'], size=n_samples, p=[0.5, 0.3, 0.2])\n",
    "user_tiers = np.random.choice(['Normal', 'VIP'], size=n_samples, p=[0.7, 0.3])\n",
    "categories = np.random.choice(['Order Related', 'Returns', 'Product Queries', 'Payments'], size=n_samples, p=[0.4, 0.3, 0.2, 0.1])\n",
    "is_repeat_caller = np.random.choice([0, 1], size=n_samples, p=[0.8, 0.2])\n",
    "\n",
    "df = pd.DataFrame({\n",
    "    'session_id': range(10000, 10000 + n_samples),\n",
    "    'market': markets,\n",
    "    'user_tier': user_tiers,\n",
    "    'category': categories,\n",
    "    'is_repeat_caller': is_repeat_caller\n",
    "})\n",
    "\n",
    "# 2. 生成带强烈情绪的仿真客诉文本（基础底噪数据）\n",
    "base_texts = {\n",
    "    'Order Related': [\n",
    "        \"when will my order arrive\", \"order delayed\", \"delivery is slow\", \n",
    "        \"thank you very nice\", \"love the product\", \"please check shipping status\",\n",
    "        \"happy with my purchase\", \"shopzilla is great\", \"did not receive my package\"\n",
    "    ],\n",
    "    'Returns': [\n",
    "        \"how to return\", \"return policy\", \"refund not received\", \"good return experience\",\n",
    "        \"wrong size send it back\", \"thanks for quick refund\", \"return portal issue\"\n",
    "    ],\n",
    "    'Product Queries': [\n",
    "        \"do you have size medium\", \"fabric details please\", \"nice dress\", \n",
    "        \"color looks different\", \"out of stock when restock\"\n",
    "    ],\n",
    "    'Payments': [\n",
    "        \"payment failed\", \"credit card not working\", \"double charged\",\n",
    "        \"smooth transaction\", \"paypal error\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "def generate_text(cat):\n",
    "    return np.random.choice(base_texts[cat])\n",
    "\n",
    "df['text'] = df['category'].apply(generate_text)\n",
    "\n",
    "# 3. 🎯 注入真实的业务断点 (The French Market URL Misconfiguration Story)\n",
    "# 背景：法国市场针对 VIP 会员上线了免费试用促销，但负责配置话术的运营团队把【付费会员专属退款 URL】配错了，\n",
    "# 导致大量 VIP 会员无法在线自助通过驿站免邮退款，不仅产生了重复进线，且产生了大量差评。\n",
    "fr_vip_return_idx = df[(df['market'] == 'FR') & (df['category'] == 'Returns') & (df['user_tier'] == 'VIP')].index\n",
    "\n",
    "fr_vip_texts = [\n",
    "    \"express station url is wrong\", \n",
    "    \"the free trial return link is broken\", \n",
    "    \"cannot click the collection url\", \n",
    "    \"promo code for return invalid on the page\",\n",
    "    \"station link error please check\"\n",
    "]\n",
    "df.loc[fr_vip_return_idx, 'text'] = np.random.choice(fr_vip_texts, size=len(fr_vip_return_idx))\n",
    "# 强制标记这批为异常重复进线，且CSAT极低\n",
    "df.loc[fr_vip_return_idx, 'is_repeat_caller'] = np.random.choice([0, 1], size=len(fr_vip_return_idx), p=[0.2, 0.8])\n",
    "df.loc[fr_vip_return_idx, 'csat_score'] = np.random.choice([1, 2], size=len(fr_vip_return_idx))\n",
    "\n",
    "# 4. 生成其貌不扬的基础 CSAT\n",
    "negative_words = ['delayed', 'slow', 'fail', 'wrong', 'broken', 'error', 'invalid', 'issue', 'not']\n",
    "def simulate_csat(txt):\n",
    "    if any(w in txt.lower() for w in negative_words):\n",
    "        return np.random.choice([1, 2, 3], p=[0.5, 0.3, 0.2])\n",
    "    else:\n",
    "        return np.random.choice([4, 5], p=[0.4, 0.6])\n",
    "\n",
    "null_csat = df['csat_score'].isna()\n",
    "df.loc[null_csat, 'csat_score'] = df.loc[null_csat, 'text'].apply(simulate_csat)\n",
    "\n",
    "df['is_negative'] = (df['csat_score'] <= 3).astype(int)\n",
    "\n",
    "display(df.head())\n",
    "print(f\"Total shape: {df.shape}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "852fe233",
   "metadata": {},
   "source": [
    "## Step 2: TF-IDF 进阶处理 (N-gram 与业务停用词)\n",
    "仅仅提取单字（如 `url`, `return`）无法定位业务问题。我们通过 `ngram_range=(1, 3)` 提取短语，同时强力过滤 `shopzilla`, `thanks` 等业务噪音。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c99242a",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS\n",
    "custom_stopwords = ['shopzilla', 'please', 'thanks', 'thank', 'you', 'very', 'did', 'is', 'the', 'my', 'to', 'for', 'with', 'on', 'have']\n",
    "all_stopwords = list(ENGLISH_STOP_WORDS) + custom_stopwords\n",
    "\n",
    "tfidf = TfidfVectorizer(\n",
    "    stop_words=all_stopwords,\n",
    "    ngram_range=(1, 3),\n",
    "    min_df=3,\n",
    "    max_features=500\n",
    ")\n",
    "\n",
    "tfidf_matrix = tfidf.fit_transform(df['text'])\n",
    "feature_names = tfidf.get_feature_names_out()\n",
    "df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)\n",
    "print(f\"提取特征词/短语数量: {len(feature_names)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "489520f9",
   "metadata": {},
   "source": [
    "## Step 3: 提取 \"纯正痛点\" (Delta 差评权重提取法)\n",
    "不区分好坏评算词频，只会被 \"nice\", \"good\" 等通用词淹没。真正的 Senior 做法是：**痛点特征 = 差评中的 TF-IDF 均值 - 好评中的 TF-IDF 均值**。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "35cf68eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_delta_keywords(df_meta, df_tfidf_features, target_category, top_n=10):\n",
    "    idx = df_meta[df_meta['category'] == target_category].index\n",
    "    if len(idx) == 0: return None\n",
    "\n",
    "    cat_tfidf = df_tfidf_features.loc[idx]\n",
    "    cat_meta = df_meta.loc[idx]\n",
    "\n",
    "    neg_idx = cat_meta[cat_meta['is_negative'] == 1].index\n",
    "    pos_idx = cat_meta[cat_meta['is_negative'] == 0].index\n",
    "\n",
    "    if len(pos_idx) == 0:\n",
    "        delta_series = df_tfidf_features.loc[neg_idx].mean()\n",
    "    else:\n",
    "        neg_mean = df_tfidf_features.loc[neg_idx].mean()\n",
    "        pos_mean = df_tfidf_features.loc[pos_idx].mean()\n",
    "        delta_series = neg_mean - pos_mean\n",
    "\n",
    "    top_words = delta_series.sort_values(ascending=False).head(top_n)\n",
    "    return top_words[top_words > 0]\n",
    "\n",
    "print(\"==== Category: Returns -> 核心纯痛点挖掘 ====\")\n",
    "returns_painpoints = extract_delta_keywords(df, df_tfidf, 'Returns')\n",
    "display(returns_painpoints.to_frame('TF-IDF Delta Score'))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4b94497c",
   "metadata": {},
   "source": [
    "## Step 4: 3D 交叉分析 (Cross-Analysis)\n",
    "单纯的转人工率没用，我们需要把**问题严重性拉满**。当一个痛点同时关联着：\n",
    "1. `user_tier = VIP`\n",
    "2. `is_repeat_caller = 1`\n",
    "那这就是 P0 级别的产品/运营断点。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "061438cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 将核心痛点词重新打回到原宽表，看看各人群受灾情况\n",
    "target_issues = ['url', 'link broken', 'station', 'trial']\n",
    "df['has_url_issue'] = df['text'].apply(lambda x: 1 if any(t in x for t in target_issues) else 0)\n",
    "\n",
    "cross_analysis = (\n",
    "    df[df['category'] == 'Returns']\n",
    "    .groupby(['market', 'user_tier'])\n",
    "    .agg(\n",
    "        total_tickets=('session_id', 'count'),\n",
    "        avg_csat=('csat_score', 'mean'),\n",
    "        repeat_call_rate=('is_repeat_caller', 'mean'),\n",
    "        url_issue_cnt=('has_url_issue', 'sum')\n",
    "    )\n",
    ").reset_index()\n",
    "\n",
    "cross_analysis['issue_penetration'] = cross_analysis['url_issue_cnt'] / cross_analysis['total_tickets']\n",
    "cross_analysis = cross_analysis.sort_values(by='issue_penetration', ascending=False)\n",
    "\n",
    "cm = sns.light_palette(\"red\", as_cmap=True)\n",
    "display(\n",
    "    cross_analysis.style.background_gradient(subset=['issue_penetration', 'repeat_call_rate'], cmap=cm)\n",
    "    .format({'avg_csat': '{:.2f}', 'repeat_call_rate': '{:.1%}', 'issue_penetration': '{:.1%}'})\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cc783bd2",
   "metadata": {},
   "source": [
    "## Step 5: 业务闭环与原声抽样 (The Delivery)\n",
    "数据分析的最后一公里，是把**原声展示给对应负责人**。通过交叉分析锁定 `FR市场` 的 `VIP用户` 存在严重的 `URL/驿站链条断裂` 问题，且引发了重复进线。捞出录音文本作为铁证。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1926bdbf",
   "metadata": {},
   "outputs": [],
   "source": [
    "raw_evidence = df[\n",
    "    (df['market'] == 'FR') & \n",
    "    (df['user_tier'] == 'VIP') & \n",
    "    (df['category'] == 'Returns') &\n",
    "    (df['has_url_issue'] == 1) &\n",
    "    (df['is_negative'] == 1)\n",
    "]\n",
    "\n",
    "print(\"🚨 [HIGH PRIORITY ALERT] 针对法国市场 VIP 退货 URL 配置错误的随机抽样验证：\")\n",
    "print(\"-\" * 80)\n",
    "for i, txt in enumerate(raw_evidence['text'].sample(n=min(5, len(raw_evidence)), random_state=42).tolist(), 1):\n",
    "    print(f\"证据 {i}: '{txt}'\")\n",
    "print(\"-\" * 80)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5c8ea70a",
   "metadata": {},
   "source": [
    "### 💡 面试实战汇报话术 (The Pitch - 紧密对齐简历)\n",
    "\n",
    "> \"通过使用 N-gram 短语提取结合 '差评与好评的情感均值 Delta 排位'（而非单纯无维度算全局词频），我避免了词频注水，在 `Returns` 品类下提取到了突发异常的痛点词 `'url wrong'`、`'express station url'`。\n",
    ">\n",
    ">随后，我抛弃了干巴巴的文本统计，建立了 **3 维特征交叉分析（客询维度 × 市场维度 × 用户忠诚度价值等级）**。结合热力图，我一眼锁定了灾害现场：在法国市场，**VIP 会员的重复进线率（Repeat Call Rate）飙升到了近 80%**，而痛点渗透率 100% 指向 `Express Station URL`。\n",
    ">\n",
    ">我秒级抽出这批高净值用户的 10 条原声文本作为证据推送给运营排查，最终查实：**活动运营给法国区不同层级会员下发不同的退货话术时，错误地为所有的 VIP 用户配置了一个失效的免费试用驿站退货 URL，导致这些大 R 用户无法在线流转，被迫反复冲击人工池寻找解决途径。**\n",
    ">\n",
    ">当天下午协同修改错配 URL 后，此场景下单周进线转人工率从 30% 迅速收敛回调至 7%，打赢了这场典型的体验降本攻坚战。\""
   ]
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
